apic:
  type: "object"
  required: true
  patternProperties:
      "^\\w+":
        "$ref": "#/properties/apics"
  additionalProperties: false

apics:
  type: "object"
  properties:
    address:
      description: "Hostname or IP address of APIC."
      type: "string"
      required: true
    user:
      description: "Authentication user-id for the APIC."
      type: "string"
      required: true
    passwd:
      description: "The password of the specified user."
      type: "string"
      secret: true
      required: true
